name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        cd C++/helloworld/third_party/gtest/
        git submodule update -i
        cd ../../
        mkdir build/
        cd build/
        cmake ..
        make
    - name: test
      run: |
        pwd
        ./test_calc
