name: CI C

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: build
      run: |
        cd C++/helloworld/
        ./build.sh
# too late... because docker re-build without cache.
#        docker build --tag ${USER}/test_c .
    - name: test
      run: |
         C++/helloworld/build/test_calc
#        docker run --rm ${USER}/test_c /workspace/helloworld/build/test_calc
